spring.application.name=chemz-backend

# ======================================================
# ? DATABASE (DigitalOcean PostgreSQL)
# ======================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ======================================================
# ? JWT CONFIG
# ======================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=21600000

server.port=8080

# ======================================================
# ? EMAIL CONFIG (Gmail App Password Required)
# ======================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${APP_EMAIL}
spring.mail.password=${APP_PASSORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ======================================================
# ? VERIFICATION CODE SETTINGS
# ======================================================
# Code expires after 10 minutes
app.verification.code-expiration-minutes=10
